// <auto-generated />
using System;
using Hotel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProjectHotel.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20251121152126_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hotel.Models.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("Capacidad")
                        .HasColumnType("smallint")
                        .HasColumnName("capacidad");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("disponible")
                        .HasColumnName("estado");

                    b.Property<string>("NumeroHabitacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("numero_habitacion");

                    b.Property<short?>("Piso")
                        .HasColumnType("smallint")
                        .HasColumnName("piso");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_base");

                    b.Property<int>("TipoHabitacionId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_habitacion_id");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("NumeroHabitacion")
                        .IsUnique();

                    b.HasIndex("TipoHabitacionId");

                    b.ToTable("habitaciones");
                });

            modelBuilder.Entity("Hotel.Models.HabitacionServicio", b =>
                {
                    b.Property<int>("HabitacionId")
                        .HasColumnType("int")
                        .HasColumnName("habitacion_id");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.HasKey("HabitacionId", "ServicioId");

                    b.HasIndex("ServicioId");

                    b.ToTable("habitacion_servicio");
                });

            modelBuilder.Entity("Hotel.Models.Huesped", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique()
                        .HasFilter("[numero_documento] IS NOT NULL");

                    b.ToTable("huespedes");
                });

            modelBuilder.Entity("Hotel.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("metodo");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notas");

                    b.Property<DateTime>("PagadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("pagado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ProcesadoPor")
                        .HasColumnType("int")
                        .HasColumnName("procesado_por");

                    b.Property<DateTime?>("ReembolsadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("reembolsado_en");

                    b.Property<string>("ReferenciaTransaccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("referencia_transaccion");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int")
                        .HasColumnName("reserva_id");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("ProcesadoPor");

                    b.HasIndex("ReservaId");

                    b.ToTable("pagos", t =>
                        {
                            t.HasCheckConstraint("CK_Pagos_Monto", "monto > 0");
                        });
                });

            modelBuilder.Entity("Hotel.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CanceladoPor")
                        .HasColumnType("int")
                        .HasColumnName("cancelado_por");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("creado_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cancelacion");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_entrada");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_salida");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int")
                        .HasColumnName("habitacion_id");

                    b.Property<int>("HuespedId")
                        .HasColumnType("int")
                        .HasColumnName("huesped_id");

                    b.Property<short>("NumeroHuespedes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("numero_huespedes");

                    b.Property<short>("NumeroNoches")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("smallint")
                        .HasColumnName("numero_noches")
                        .HasComputedColumnSql("DATEDIFF(DAY, fecha_entrada, fecha_salida)", true);

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_por_noche");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_total");

                    b.HasKey("Id");

                    b.HasIndex("CanceladoPor");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("Estado");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("HuespedId");

                    b.HasIndex("FechaEntrada", "FechaSalida");

                    b.ToTable("reservas", t =>
                        {
                            t.HasCheckConstraint("CK_Reservas_FechaSalida", "fecha_salida > fecha_entrada");

                            t.HasCheckConstraint("CK_Reservas_NumeroHuespedes", "numero_huespedes > 0");

                            t.HasCheckConstraint("CK_Reservas_PrecioPorNoche", "precio_por_noche > 0");

                            t.HasCheckConstraint("CK_Reservas_PrecioTotal", "precio_total > 0");
                        });
                });

            modelBuilder.Entity("Hotel.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Icono")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("icono");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("servicios");
                });

            modelBuilder.Entity("Hotel.Models.TemporadaHabitacionPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int")
                        .HasColumnName("habitacion_id");

                    b.Property<decimal>("PrecioOverride")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_override");

                    b.Property<int>("TemporadaId")
                        .HasColumnType("int")
                        .HasColumnName("temporada_id");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("TemporadaId");

                    b.HasIndex("TemporadaId", "HabitacionId")
                        .IsUnique();

                    b.ToTable("temporada_habitacion_precios", t =>
                        {
                            t.HasCheckConstraint("CK_TemporadaPrecios_Precio", "precio_override > 0");
                        });
                });

            modelBuilder.Entity("Hotel.Models.TemporadaPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("FactorMultiplicador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(1.00m)
                        .HasColumnName("factor_multiplicador");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("FechaInicio", "FechaFin");

                    b.ToTable("TemporadasPrecio", t =>
                        {
                            t.HasCheckConstraint("CK_Temporadas_Factor", "factor_multiplicador > 0");

                            t.HasCheckConstraint("CK_Temporadas_FechaFin", "fecha_fin >= fecha_inicio");
                        });
                });

            modelBuilder.Entity("Hotel.Models.TipoHabitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tipos_habitacion");
                });

            modelBuilder.Entity("Hotel.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Rol");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Hotel.Models.Habitacion", b =>
                {
                    b.HasOne("Hotel.Models.TipoHabitacion", "TipoHabitacion")
                        .WithMany("Habitaciones")
                        .HasForeignKey("TipoHabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoHabitacion");
                });

            modelBuilder.Entity("Hotel.Models.HabitacionServicio", b =>
                {
                    b.HasOne("Hotel.Models.Habitacion", "Habitacion")
                        .WithMany("HabitacionServicios")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel.Models.Servicio", "Servicio")
                        .WithMany("HabitacionServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Hotel.Models.Pago", b =>
                {
                    b.HasOne("Hotel.Models.Usuario", "UsuarioProcesador")
                        .WithMany("PagosProcesados")
                        .HasForeignKey("ProcesadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hotel.Models.Reserva", "Reserva")
                        .WithMany("Pagos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("UsuarioProcesador");
                });

            modelBuilder.Entity("Hotel.Models.Reserva", b =>
                {
                    b.HasOne("Hotel.Models.Usuario", "UsuarioCancelador")
                        .WithMany("ReservasCanceladas")
                        .HasForeignKey("CanceladoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hotel.Models.Usuario", "UsuarioCreador")
                        .WithMany("ReservasCreadas")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hotel.Models.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hotel.Models.Huesped", "Huesped")
                        .WithMany("Reservas")
                        .HasForeignKey("HuespedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Huesped");

                    b.Navigation("UsuarioCancelador");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("Hotel.Models.TemporadaHabitacionPrecio", b =>
                {
                    b.HasOne("Hotel.Models.Habitacion", "Habitacion")
                        .WithMany("TemporadaPrecios")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel.Models.TemporadaPrecio", "Temporada")
                        .WithMany("HabitacionPrecios")
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("Hotel.Models.Habitacion", b =>
                {
                    b.Navigation("HabitacionServicios");

                    b.Navigation("Reservas");

                    b.Navigation("TemporadaPrecios");
                });

            modelBuilder.Entity("Hotel.Models.Huesped", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Hotel.Models.Reserva", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Hotel.Models.Servicio", b =>
                {
                    b.Navigation("HabitacionServicios");
                });

            modelBuilder.Entity("Hotel.Models.TemporadaPrecio", b =>
                {
                    b.Navigation("HabitacionPrecios");
                });

            modelBuilder.Entity("Hotel.Models.TipoHabitacion", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("Hotel.Models.Usuario", b =>
                {
                    b.Navigation("PagosProcesados");

                    b.Navigation("ReservasCanceladas");

                    b.Navigation("ReservasCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
